In [29]:
import numpy as np

A = np.array(
    [[0, 1],
     [2, 3],
     [4, 5]])
B = np.array(
    [[0, 1, 2, 3],
     [4, 5, 6, 7]])
AB = np.dot(A, B)
## 行列の積の計算結果
print('行列の積の計算結果は以下です')
print(AB)

## 最大値の計算結果
max_AB = np.max(AB)
print(f'行列の要素の最大値は{max_AB}です')

行列の積の計算結果は以下です
[[ 4  5  6  7]
 [12 17 22 27]
 [20 29 38 47]]
行列の要素の最大値は47です
